name: chart
image:
  tag: latest
  repository: chart
  imagePullPolicy: Always

replicas: 1

service:
  port: 3000
  targetPort: 3000
  type: LoadBalancer

probe:
  liveness: /probe/liveness
  readiness: /probe/readiness

exampleVar: "Some default value"
