apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.replicas }}
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probe.readiness }}
            port: {{ .Values.service.targetPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probe.liveness }}
            port: {{ .Values.service.targetPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-env